#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# FLT=«path-to-FLT-repo»
# DST=«path-to-destination»
# TGT=«target»
# EXT=«target-executable-extension»
# OUT=«target-filename-case-upper-or-lower»

XCC=~/Documents/development/cc65
FLT=~/Documents/development/FLT
DST=./atari
TGT=atari
EXT=xex
OUT=upper

# Build the executable $L
source ./build-cc65-common

# Move and copy to the destination
# Note file names in uppercase, but contents in lowercase, and special LF of 0x9B!
mv $L $DST/
for F in *.LISP ; do tr '[A-Z]' '[a-z]' < $F | tr '\n' '\233' > $DST/$(xform $F) ; done

# Rename the files to 8.3 format, for now just need to remove vowels from right to left
cd $DST
V=$(xform AEIOU)
for i in {1..3} ; do rename -f "s/(\w*)[$V]+([^$V]*)\.(.*)/\1\2.\3/g" ?????????*.* ; done
for i in {1..2} ; do rename -f "s/(.*)\.(\w*)[$V]+([^$V]*)/\1.\2\3/g" *.????* ; done

# Run the emulator
atari800 -atari -800-rev altirra -H1 ./ -run $L >/dev/null 2>&1
