#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# FLT=«path-to-FLT-repo»
# DST=«path-to-destination»
# TGT=«target»
# EXT=«target-executable-extension»
# OUT=«target-filename-case-upper-or-lower»

XCC=~/Documents/development/cc65
FLT=~/Documents/development/FLT
DST=./c64
TGT=c64
EXT=prg
OUT=lower

# Build the executable $L
source ./build-cc65-common

# Move and copy to the destination
mv $L $DST/
for F in *.LISP ; do cp $F $DST/$(xform $F) ; done

# Create a D64 image if c1541 is available
cd $DST
if command -v c1541 >/dev/null ; then
	# Build up the write commands
	W="-write $L" ; for F in *.LISP ; do W="$W -write $(xform $F)" ; done
	# Create a D64 image in the destination
	c1541 -format lisp,2a d64 lisp.d64 -attach lisp.d64 8 $W
fi

# Run the emulator
vice-jz.x64 -silent 2> /dev/null
