#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# FLT=«path-to-FLT-repo»
# DST=«path-to-destination»
# TGT=«target»
# EXT=«target-executable-extension»
# OUT=«target-filename-case-upper-or-lower»

XCC=~/Documents/development/cc65
FLT=~/Documents/development/FLT
DST=~/Documents/development/x16emu_linux-x86_64-r49
TGT=cx16
EXT=prg
OUT=upper

# Build the executable $L
source ./build-cc65-common

# Move and copy to the destination
mv $L $DST/
for F in *.LISP ; do cp $F $DST/$(xform $F) ; done

# Run the emulator
cd $DST
./x16emu -scale 2 -mhz 16 -prg $L -run
