#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# FLT=«path-to-FLT-repo»
# DST=«path-to-destination»
# TGT=«target»
# EXT=«target-executable-extension»
# OUT=«target-filename-case-upper-or-lower»

XCC=~/Documents/development/cc65
FLT=~/Documents/development/FLT
DST=./atari
TGT=atari
EXT=xex
OUT=upper

xform() {
    local x="$1"

    if [[ $OUT == upper ]] ; then
        echo "${x^^}"
    else
        echo "${x,,}"
    fi
}

# Build lisp / use -DTRACE to enable tracing
C=lisp
L=$(xform $C.$EXT)
php $FLT/flt/flt.php -i tinylisp-cc65.c -o tinylisp-cc65-flt.c -x "-D__${TGT^^}__ -DNOTRACE -I $XCC/include -I $FLT/flt"
$XCC/bin/cc65 -t $TGT -D__${TGT^^}__ -DNOTRACE -I $XCC/include tinylisp-cc65-flt.c
$XCC/bin/ca65 -t $TGT tinylisp-cc65-flt.s
$XCC/bin/ld65 -o $L -t $TGT tinylisp-cc65-flt.o -L $FLT/flt flt-$TGT.lib -L $XCC/lib $TGT.lib

# Clean up
rm *-flt.c *.s *.o

# Create the destination if not present
mkdir -p $DST

# Move and copy to the destination. Note file names in uppercase, but content in lowercase, and special LF!
mv $L $DST/
for F in *.LISP ; do tr '[A-Z]' '[a-z]' < $F | tr '\n' '\233' > $DST/$(xform $F) ; done

# Rename the files to 8.3 format, for now just need to remove vowels from right to left
cd $DST
V=$(xform AEIOU)
for i in {1..3} ; do rename -f "s/(\w*)[$V]+([^$V]*)\.(.*)/\1\2.\3/g" ?????????*.* ; done
for i in {1..2} ; do rename -f "s/(.*)\.(\w*)[$V]+([^$V]*)/\1.\2\3/g" *.????* ; done

# Run the emulator
atari800 -atari -800-rev altirra -H1 ./ -run $L
