#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# FLT=«path-to-FLT-repo»
# DST=«path-to-destination»
# TGT=«target»
# EXT=«target-executable-extension»
# OUT=«target-filename-case-upper-or-lower»

XCC=~/Documents/development/cc65
FLT=~/Documents/development/FLT
DST=./c64
TGT=c64
EXT=prg
OUT=lower

xform() {
    local x="$1"

    if [[ $OUT == upper ]] ; then
        echo "${x^^}"
    else
        echo "${x,,}"
    fi
}

# Build lisp / use -DTRACE to enable tracing
C=lisp
L=$(xform $C.$EXT)
php $FLT/flt/flt.php -i tinylisp-cc65.c -o tinylisp-cc65-flt.c -x "-D__${TGT^^}__ -DNOTRACE -I $XCC/include -I $FLT/flt"
$XCC/bin/cc65 -t $TGT -D__${TGT^^}__ -DNOTRACE -I $XCC/include tinylisp-cc65-flt.c
$XCC/bin/ca65 -t $TGT tinylisp-cc65-flt.s
$XCC/bin/ld65 -o $L -t $TGT tinylisp-cc65-flt.o -L $FLT/flt flt-$TGT.lib -L $XCC/lib $TGT.lib

# Clean up
rm *-flt.c *.s *.o

# Create the destination if not present
mkdir -p $DST

# Move and copy to the destination
mv $L $DST/
for F in *.LISP ; do cp $F $DST/$(xform $F) ; done

# Create a D64 image if c1541 is available
if command -v c1541 >/dev/null ; then
	# Build up the write commands
	W="-write $L" ; for F in *.LISP ; do W="$W -write $(xform $F)" ; done
	# Create a D64 image in the destination
	cd $DST
	c1541 -format lisp,2a d64 lisp.d64 -attach lisp.d64 8 $W
fi
