#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# FLT=«path-to-FLT-repo»
# DST=«path-to-destination»

XCC=~/Documents/development/cc65
FLT=~/Documents/development/FLT
DST=./c64

# Build lisp.prg / use -DTRACE to enable tracing
php $FLT/flt/flt.php -i tinylisp-cc65.c -o tinylisp-cc65-flt.c -x "-D__C64__ -DNOTRACE -I $XCC/include -I $FLT/flt"
$XCC/bin/cc65 -t c64 -D__C64__ -DNOTRACE -I $XCC/include tinylisp-cc65-flt.c
$XCC/bin/ca65 -t c64 tinylisp-cc65-flt.s
$XCC/bin/ld65 -o lisp.prg -t c64 tinylisp-cc65-flt.o -L $FLT/flt flt.lib -L $XCC/lib c64.lib

# Create the destination if not present
mkdir -p $DST

# Move and copy to the destination
mv lisp.prg $DST/
for F in *.LISP ; do cp $F $DST/${F,,} ; done

# Clean up
rm *-flt.c *.s *.o
