#!/bin/bash

if [[ -z $TGT ]]; then
	echo "This script should not be run by itself!"
	exit;
fi

if [[ ! -f $FLT/flt/flt-$TGT.lib ]] ; then
	echo "Build flt-$TGT.lib first!"
	exit
fi

xform() {
	local x="$1"

	if [[ $OUT == upper ]] ; then
		echo "${x^^}"
	else
		echo "${x,,}"
	fi
}

# Build lisp / use -DTRACE to enable tracing
C=lisp
L=$(xform $C.$EXT)
php $FLT/flt/flt.php -i tinylisp-cc65.c -o tinylisp-cc65-flt.c -x "-D__${TGT^^}__ -DNOTRACE -I $XCC/include -I $FLT/flt"
$XCC/bin/cc65 -t $TGT -D__${TGT^^}__ -DNOTRACE -I $XCC/include tinylisp-cc65-flt.c
$XCC/bin/ca65 -t $TGT tinylisp-cc65-flt.s
$XCC/bin/ld65 -o $L -t $TGT tinylisp-cc65-flt.o -L $FLT/flt flt-$TGT.lib -L $XCC/lib $TGT.lib

# Clean up
rm *-flt.c *.s *.o

# Create the destination if not present
mkdir -p $DST
